import type { Car } from "./types"

export const cars: Car[] = [
  {
    id: "19",
    name: "Lamborghini Urus SE",
    brand: "Lamborghini",
    category: "SUV",
    year: 2024,
    price: 310000,
    priceWithVat: 310000, // VAT CAR - price already includes VAT
    image: "/cars/lamborghini-urus-se.jpg",
    rating: 4.9,
    transmission: "Automatic",
    color: "Bianco Monocerus",
    featured: true,
    description: "The ultimate luxury SUV with hybrid technology. VIN: ZPBED5ZL3SLA37204. Available NOW with €10,000 deposit. VAT included.",
    specifications: {
      engine: "4.0L Twin-Turbo V8 + Electric",
      power: "800 HP",
      acceleration: "3.4s (0-60 mph)",
      topSpeed: "190 mph",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD",
      fuelEconomy: "16 city / 22 highway mpg",
      seating: "5 passengers"
    }
  },
  {
    id: "1",
    name: "Bentley Continental GT V8",
    brand: "Bentley",
    category: "Coupe",
    year: 2024,
    price: 245000,
    priceWithVat: 294000,
    discountPrice: 235000,
    discountPriceWithVat: 282000,
    image: "/cars/bentley-continental.png",
    rating: 4.9,
    transmission: "Automatic",
    color: "Onyx Black",
    featured: true,
    description: "The pinnacle of British luxury and performance, the Continental GT V8 combines exquisite craftsmanship with exhilarating driving dynamics.",
    specifications: {
      engine: "4.0L Twin-Turbo V8",
      power: "542 HP",
      acceleration: "3.9s (0-60 mph)",
      topSpeed: "198 mph",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD",
      fuelEconomy: "18 city / 28 highway mpg",
      seating: "4 passengers"
    }
  },
  {
    id: "2",
    name: "Rolls-Royce Phantom VIII",
    brand: "Rolls-Royce",
    category: "Sedan",
    year: 2024,
    price: 485000,
    priceWithVat: 582000,
    image: "/cars/rolls-royce-ghost.png",
    rating: 5.0,
    transmission: "Automatic",
    color: "Arctic White",
    featured: true,
    description: "The ultimate expression of luxury motoring, the Phantom VIII sets the standard for refinement and prestige.",
    specifications: {
      engine: "6.75L Twin-Turbo V12",
      power: "563 HP",
      acceleration: "5.1s (0-60 mph)",
      topSpeed: "155 mph",
      transmission: "8-Speed Automatic",
      drivetrain: "RWD",
      fuelEconomy: "12 city / 18 highway mpg",
      seating: "5 passengers"
    }
  },
  {
    id: "3",
    name: "Lamborghini Huracán EVO",
    brand: "Lamborghini",
    category: "Supercar",
    year: 2024,
    price: 230000,
    priceWithVat: 276000,
    image: "/cars/lamborghini-urus.png",
    rating: 4.8,
    transmission: "Automatic",
    color: "Arancio Borealis",
    featured: true,
    description: "Italian craftsmanship meets cutting-edge technology in this naturally aspirated V10 masterpiece.",
    specifications: {
      engine: "5.2L Naturally Aspirated V10",
      power: "630 HP",
      acceleration: "2.9s (0-60 mph)",
      topSpeed: "202 mph",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "AWD",
      fuelEconomy: "13 city / 18 highway mpg",
      seating: "2 passengers"
    }
  },
  {
    id: "4",
    name: "Mercedes-AMG GT 63 S",
    brand: "Mercedes",
    category: "Coupe",
    year: 2024,
    price: 175000,
    priceWithVat: 210000,
    discountPrice: 165000,
    discountPriceWithVat: 198000,
    image: "/cars/mercedes-amg-gt.png",
    rating: 4.7,
    transmission: "Automatic",
    color: "Magnetite Black",
    featured: false,
    description: "A four-door coupe that redefines the balance between everyday usability and track-focused performance.",
    specifications: {
      engine: "4.0L Twin-Turbo V8",
      power: "630 HP",
      acceleration: "3.1s (0-60 mph)",
      topSpeed: "195 mph",
      transmission: "9-Speed Automatic",
      drivetrain: "AWD",
      fuelEconomy: "15 city / 22 highway mpg",
      seating: "4 passengers"
    }
  },
  {
    id: "5",
    name: "BMW M8 Competition",
    brand: "BMW",
    category: "Coupe",
    year: 2023,
    price: 145000,
    priceWithVat: 174000,
    image: "/cars/bmw-7-series.png",
    rating: 4.6,
    transmission: "Automatic",
    color: "Alpine White",
    featured: false,
    description: "BMW's flagship performance coupe delivers exceptional power and precision engineering.",
    specifications: {
      engine: "4.4L Twin-Turbo V8",
      power: "617 HP",
      acceleration: "3.0s (0-60 mph)",
      topSpeed: "190 mph",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD",
      fuelEconomy: "15 city / 22 highway mpg",
      seating: "4 passengers"
    }
  },
  {
    id: "6",
    name: "Aston Martin DB11 V12",
    brand: "Aston Martin",
    category: "Coupe",
    year: 2024,
    price: 220000,
    priceWithVat: 264000,
    image: "/luxury-coupe.png",
    rating: 4.8,
    transmission: "Automatic",
    color: "British Racing Green",
    featured: true,
    description: "Timeless British elegance meets modern performance in this stunning grand tourer.",
    specifications: {
      engine: "5.2L Twin-Turbo V12",
      power: "630 HP",
      acceleration: "3.5s (0-60 mph)",
      topSpeed: "208 mph",
      transmission: "8-Speed Automatic",
      drivetrain: "RWD",
      fuelEconomy: "15 city / 22 highway mpg",
      seating: "4 passengers"
    }
  },
  {
    id: "7",
    name: "Porsche 911 Turbo S",
    brand: "Porsche",
    category: "Sports Car",
    year: 2024,
    price: 230000,
    priceWithVat: 276000,
    image: "/cars/porsche-911.png",
    rating: 4.9,
    transmission: "Automatic",
    color: "Guards Red",
    featured: true,
    description: "The benchmark for sports car excellence, combining everyday usability with track-ready performance.",
    specifications: {
      engine: "3.8L Twin-Turbo Flat-6",
      power: "640 HP",
      acceleration: "2.6s (0-60 mph)",
      topSpeed: "205 mph",
      transmission: "8-Speed PDK",
      drivetrain: "AWD",
      fuelEconomy: "18 city / 24 highway mpg",
      seating: "4 passengers"
    }
  },
  {
    id: "8",
    name: "Ferrari F8 Tributo",
    brand: "Ferrari",
    category: "Supercar",
    year: 2023,
    price: 280000,
    priceWithVat: 336000,
    image: "/cars/ferrari-roma.png",
    rating: 4.9,
    transmission: "Automatic",
    color: "Rosso Corsa",
    featured: true,
    description: "A tribute to Ferrari's most powerful V8 engine, delivering pure Italian passion and performance.",
    specifications: {
      engine: "3.9L Twin-Turbo V8",
      power: "710 HP",
      acceleration: "2.9s (0-60 mph)",
      topSpeed: "211 mph",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "RWD",
      fuelEconomy: "15 city / 19 highway mpg",
      seating: "2 passengers"
    }
  },
  {
    id: "9",
    name: "Range Rover Autobiography",
    brand: "Land Rover",
    category: "SUV",
    year: 2024,
    price: 125000,
    priceWithVat: 150000,
    image: "/luxury-suv.png",
    rating: 4.5,
    transmission: "Automatic",
    color: "Santorini Black",
    featured: false,
    description: "The ultimate luxury SUV, combining unparalleled comfort with exceptional off-road capability.",
    specifications: {
      engine: "5.0L Supercharged V8",
      power: "518 HP",
      acceleration: "5.0s (0-60 mph)",
      topSpeed: "155 mph",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD",
      fuelEconomy: "14 city / 19 highway mpg",
      seating: "5 passengers"
    }
  },
  {
    id: "10",
    name: "McLaren 720S",
    brand: "McLaren",
    category: "Supercar",
    year: 2023,
    price: 315000,
    priceWithVat: 378000,
    discountPrice: 295000,
    discountPriceWithVat: 354000,
    image: "/white-sports-car-hero.jpeg",
    rating: 4.8,
    transmission: "Automatic",
    color: "Papaya Orange",
    featured: true,
    description: "British engineering excellence in its purest form, delivering otherworldly performance and precision.",
    specifications: {
      engine: "4.0L Twin-Turbo V8",
      power: "710 HP",
      acceleration: "2.8s (0-60 mph)",
      topSpeed: "212 mph",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "RWD",
      fuelEconomy: "15 city / 22 highway mpg",
      seating: "2 passengers"
    }
  },
  {
    id: "11",
    name: "Bugatti Chiron Sport",
    brand: "Bugatti",
    category: "Hypercar",
    year: 2024,
    price: 3200000,
    priceWithVat: 3840000,
    image: "/lycan-hypersport-concept.png",
    rating: 5.0,
    transmission: "Automatic",
    color: "French Racing Blue",
    featured: true,
    description: "The pinnacle of automotive engineering, representing the ultimate fusion of luxury and speed.",
    specifications: {
      engine: "8.0L Quad-Turbo W16",
      power: "1479 HP",
      acceleration: "2.3s (0-60 mph)",
      topSpeed: "261 mph",
      transmission: "7-Speed Dual-Clutch",
      drivetrain: "AWD",
      fuelEconomy: "9 city / 14 highway mpg",
      seating: "2 passengers"
    }
  },
  {
    id: "12",
    name: "Maserati MC20",
    brand: "Maserati",
    category: "Supercar",
    year: 2024,
    price: 225000,
    priceWithVat: 270000,
    image: "/cars/maserati-mc20-main.jpg",
    rating: 4.7,
    transmission: "Automatic",
    color: "Bianco Audace",
    featured: false,
    description: "Italian passion meets cutting-edge technology in this stunning mid-engine masterpiece.",
    specifications: {
      engine: "3.0L Twin-Turbo V6",
      power: "621 HP",
      acceleration: "2.9s (0-60 mph)",
      topSpeed: "202 mph",
      transmission: "8-Speed Dual-Clutch",
      drivetrain: "RWD",
      fuelEconomy: "13 city / 18 highway mpg",
      seating: "2 passengers"
    }
  },
  {
    id: "13",
    name: "Audi RS e-tron GT",
    brand: "Audi",
    category: "Electric",
    year: 2024,
    price: 145000,
    priceWithVat: 174000,
    image: "/cars/audi-r8.png",
    rating: 4.6,
    transmission: "Automatic",
    color: "Kemora Gray",
    featured: false,
    description: "The future of luxury performance, combining sustainable technology with Audi's legendary engineering.",
    specifications: {
      engine: "Dual Electric Motors",
      power: "637 HP",
      acceleration: "3.1s (0-60 mph)",
      topSpeed: "155 mph",
      transmission: "2-Speed Automatic",
      drivetrain: "AWD",
      fuelEconomy: "107 MPGe combined",
      seating: "4 passengers"
    }
  },
  {
    id: "14",
    name: "Koenigsegg Regera",
    brand: "Koenigsegg",
    category: "Hypercar",
    year: 2023,
    price: 1900000,
    priceWithVat: 2280000,
    image: "/white-luxury-porsche.png",
    rating: 5.0,
    transmission: "Direct Drive",
    color: "Carbon Fiber",
    featured: true,
    description: "Revolutionary Swedish engineering that redefines what's possible in automotive performance.",
    specifications: {
      engine: "5.0L Twin-Turbo V8 + Electric",
      power: "1500 HP",
      acceleration: "2.8s (0-60 mph)",
      topSpeed: "249 mph",
      transmission: "Direct Drive",
      drivetrain: "RWD",
      fuelEconomy: "12 city / 16 highway mpg",
      seating: "2 passengers"
    }
  },
  {
    id: "15",
    name: "Pagani Huayra BC",
    brand: "Pagani",
    category: "Hypercar",
    year: 2024,
    price: 2800000,
    priceWithVat: 3360000,
    image: "/luxury-convertible.png",
    rating: 5.0,
    transmission: "Manual",
    color: "Tricolore",
    featured: true,
    description: "Automotive art in its purest form, where every detail is crafted with obsessive attention to perfection.",
    specifications: {
      engine: "6.0L Twin-Turbo V12",
      power: "791 HP",
      acceleration: "3.0s (0-60 mph)",
      topSpeed: "238 mph",
      transmission: "7-Speed Manual",
      drivetrain: "RWD",
      fuelEconomy: "10 city / 15 highway mpg",
      seating: "2 passengers"
    }
  },
  {
    id: "16",
    name: "Tesla Model S Plaid",
    brand: "Tesla",
    category: "Electric",
    year: 2024,
    price: 110000,
    priceWithVat: 132000,
    image: "/cars/porsche-taycan.png",
    rating: 4.4,
    transmission: "Automatic",
    color: "Pearl White",
    featured: false,
    description: "Revolutionary electric performance that challenges traditional notions of luxury and speed.",
    specifications: {
      engine: "Tri-Motor Electric",
      power: "1020 HP",
      acceleration: "1.9s (0-60 mph)",
      topSpeed: "200 mph",
      transmission: "Single-Speed",
      drivetrain: "AWD",
      fuelEconomy: "120 MPGe combined",
      seating: "5 passengers"
    }
  },
  {
    id: "17",
    name: "Lexus LC 500",
    brand: "Lexus",
    category: "Coupe",
    year: 2024,
    price: 95000,
    priceWithVat: 114000,
    image: "/luxury-sedan.png",
    rating: 4.5,
    transmission: "Automatic",
    color: "Structural Blue",
    featured: false,
    description: "Japanese craftsmanship and reliability meets stunning design and natural aspiration.",
    specifications: {
      engine: "5.0L Naturally Aspirated V8",
      power: "471 HP",
      acceleration: "4.4s (0-60 mph)",
      topSpeed: "168 mph",
      transmission: "10-Speed Automatic",
      drivetrain: "RWD",
      fuelEconomy: "16 city / 25 highway mpg",
      seating: "4 passengers"
    }
  },
  {
    id: "18",
    name: "Jaguar F-Type R",
    brand: "Jaguar",
    category: "Convertible",
    year: 2023,
    price: 105000,
    priceWithVat: 126000,
    discountPrice: 98000,
    discountPriceWithVat: 117600,
    image: "/cars/bmw-x7.png",
    rating: 4.6,
    transmission: "Automatic",
    color: "British Racing Green",
    featured: false,
    description: "British sports car heritage reimagined for the modern era with stunning design and thrilling performance.",
    specifications: {
      engine: "5.0L Supercharged V8",
      power: "575 HP",
      acceleration: "3.5s (0-60 mph)",
      topSpeed: "186 mph",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD",
      fuelEconomy: "15 city / 23 highway mpg",
      seating: "2 passengers"
    }
  }
]
